version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Build message
          command: echo "Build Job"
      - run:
          name: Print the Current Time
          command: date
  pre_deploy:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Pre deploy message
          command: echo "Pre Deploy Job"
      - run:
          name: Print new version
          command: |
            NEW_VERSION=$(echo ${CIRCLE_BRANCH} | sed 's/.*-\([0-9.]\+\)$/\1/');
            echo ${NEW_VERSION}
  deploy:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Deploy message
          command: echo "Deploy Job"
      - run:
          name: Print tag
          command: echo ${CIRCLE_TAG}


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - pre_deploy:
          requires:
            - build
          filters:
            branches:
              only: /^bump-version-[0-9.]+$/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9.]+(?:-[0-9]+)?$/
            branches:
              ignore: /.*/
